Repository MohamedNiaissa/Restautomatique, pull requests merged in 2023-02, with the labels that each got.

#1 Setup
  pom.xml
  src/main/java/com/example/restautomatique/HomeRestau.java
  src/main/java/com/example/restautomatique/StarterApplication.java
  src/main/java/com/example/restautomatique/controller/RestauController.java
  src/main/java/module-info.java
  src/main/resources/com/example/restautomatique/MainView.fxml
  src/main/resources/com/example/restautomatique/hello-view.fxml
Labels: setup

#2 Add all class
  src/main/java/com/example/restautomatique/model/Commande.java
  src/main/java/com/example/restautomatique/model/Employe.java
  src/main/java/com/example/restautomatique/model/Plat.java
  src/main/java/com/example/restautomatique/model/Table.java
Labels: setup

#3 Change MainView
  src/main/resources/com/example/restautomatique/MainView.fxml
Labels: setup

#6 Fix include in .fxml
  src/main/resources/com/example/restautomatique/MainView.fxml
Labels: bug

#14 Feature: Javadoc comments and generated folder
  Javadoc Restautomatique/allclasses-index.html
  Javadoc Restautomatique/allpackages-index.html
  Javadoc Restautomatique/com/example/restautomatique/model/Commande.html
  Javadoc Restautomatique/com/example/restautomatique/model/Employe.html
  Javadoc Restautomatique/com/example/restautomatique/model/Plat.html
  Javadoc Restautomatique/com/example/restautomatique/model/Table.html
  Javadoc Restautomatique/com/example/restautomatique/model/package-summary.html
  Javadoc Restautomatique/com/example/restautomatique/model/package-tree.html
  Javadoc Restautomatique/element-list
  Javadoc Restautomatique/help-doc.html
  Javadoc Restautomatique/index-all.html
  Javadoc Restautomatique/index.html
  Javadoc Restautomatique/jquery-ui.overrides.css
  Javadoc Restautomatique/legal/COPYRIGHT
  Javadoc Restautomatique/legal/LICENSE
  Javadoc Restautomatique/legal/jquery.md
  Javadoc Restautomatique/legal/jqueryUI.md
  Javadoc Restautomatique/member-search-index.js
  Javadoc Restautomatique/module-search-index.js
  Javadoc Restautomatique/overview-tree.html
  Javadoc Restautomatique/package-search-index.js
  Javadoc Restautomatique/resources/glass.png
  Javadoc Restautomatique/resources/x.png
  Javadoc Restautomatique/script-dir/images/ui-bg_glass_55_fbf9ee_1x400.png
  Javadoc Restautomatique/script-dir/images/ui-bg_glass_65_dadada_1x400.png
  Javadoc Restautomatique/script-dir/images/ui-bg_glass_75_dadada_1x400.png
  Javadoc Restautomatique/script-dir/images/ui-bg_glass_75_e6e6e6_1x400.png
  Javadoc Restautomatique/script-dir/images/ui-bg_glass_95_fef1ec_1x400.png
  Javadoc Restautomatique/script-dir/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  Javadoc Restautomatique/script-dir/images/ui-icons_222222_256x240.png
  Javadoc Restautomatique/script-dir/images/ui-icons_2e83ff_256x240.png
  Javadoc Restautomatique/script-dir/images/ui-icons_454545_256x240.png
  Javadoc Restautomatique/script-dir/images/ui-icons_888888_256x240.png
  Javadoc Restautomatique/script-dir/images/ui-icons_cd0a0a_256x240.png
  Javadoc Restautomatique/script-dir/jquery-3.5.1.min.js
  Javadoc Restautomatique/script-dir/jquery-ui.min.css
  Javadoc Restautomatique/script-dir/jquery-ui.min.js
  Javadoc Restautomatique/script-dir/jquery-ui.structure.min.css
  Javadoc Restautomatique/script.js
  Javadoc Restautomatique/search.js
  Javadoc Restautomatique/stylesheet.css
  Javadoc Restautomatique/tag-search-index.js
  Javadoc Restautomatique/type-search-index.js
  src/main/java/com/example/restautomatique/model/Commande.java
  src/main/java/com/example/restautomatique/model/Employe.java
  src/main/java/com/example/restautomatique/model/Plat.java
  src/main/java/com/example/restautomatique/model/Table.java
Labels: documentation
